name: Release

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

on:
  push:
    branches: [ main ]

jobs:
  publish-release-packages:
    name: Publish Packages
    environment: package-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "NPM Install, Build, and Cache"
        id: npm-install-build-and-cache
        uses: ./.github/actions/npm-install-build-and-cache

      - name: Publish
        run: |
          git config --global user.email "github-ci@mml.io"
          git config --global user.name "github-ci-mml"

          # Set up npm auth token from secret for publishing
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"

          npm publish --tag latest --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
